### ISSUE TITLE
[Question] Retrieve timestamp from frame

### ISSUE THREAD

**Issue by JavierCorado** [christoph2/pyxcp#141]
While looking at the documentation it mentions that after the identification and before the data fields there is a timestamp in the XCP message frame.

Is there a method inside the master that could achieve this? Or would we have to retrieve the raw data to access this value? This would be for DAQ and polling

I noticed that in the base transport layer, there is a timestamp, but is this the same one that I am referring to?

![image](https://github.com/christoph2/pyxcp/assets/39791730/4025a88e-978d-43db-9f96-582e513bc862)

**Comment by christoph2** [comment]
Well, there's a more or less confusing hierarchy of timestamps:

- timestamps as depicted above only apply to DAQ/STIM packets and are generated by your ECU or simulator; extraction is currently left to the user (maybe there will be an API).
- pyxcp generates its own timestamps on every frame received, accessible to the user.

But the story continues, hardware interfaces may also generate timestamps (these clock-sources are currently NOT provided by pyxcp), for example  
 - s. [CANlib documentation on time measurement](https://pycanlib.readthedocs.io/en/v1.18.846/canlib/timemeasurement.html)
 - Starting with Windows 11, there is support for (fairly complex) UDP cross-timestamping (Precision Time Protocol).
