### ISSUE TITLE
Python 3.12 wheels

### ISSUE THREAD

**Issue by chrisoro** [christoph2/pyxcp#147]
Would it be possible to also provide wheels for 3.12? Unfortunately, I'm unable to modify or test the workflows on a fork, so I can only request this via a ticket. 

Upon reviewing your project, it seems that all you need to do is upgrade to a more recent version of cibuildwheel (2.16 or higher to support 3.12) and adjust the configuration accordingly.

**Comment by christoph2** [comment]
OK, done.
3.12 support is now available on PyPI.

**Comment by chrisoro** [comment]
Awesome, thank you!
