### ISSUE TITLE
pyxcp build error with pip in ubuntu

### ISSUE THREAD

**Issue by JavierCorado** [christoph2/pyxcp#167]
Attempted to install the latest version of pyxcp (v0.22.1) with pip (pip install pyxcp) and there are issues while building the package:

![image](https://github.com/user-attachments/assets/208bbc8d-779f-4e67-bf73-89e139a8613e)

Saw this in both ubuntu WSL and ubuntu version 22.04.1 running on: x86_64 x86_64 x86_64 GNU/Linux

**Comment by christoph2** [comment]
Hello,

The build-system requires `cmake`, which is missing in your case.

Building pyXCP  on Linux  is a bit tricky, so I did some Docker experiments and came to the following requirements:

```shell
sudo apt install -y pkg-config
sudo apt install -y gcc git libssl-dev python3 python3-pip python3-poetry rustc cargo libffi-dev cmake
````

And yes, there is a pro-forma source distro for `v22.1`  on pypi, but I doubt it is complete, so you should 
start with a cloned/forked repo.


There will be some smaller updates in the next time (including pre-build Linux packages), so make sure 
to install pyXCP in editable mode:

```shell
pip3 install -e .
```

The next thing I observed on Linix:
Even if `poetry` should install `pybind11`, `cmake`  may unable to locate it, in this case, just manually

```python
pip3 install pybind11
```

Hope it helps.

**Comment by JavierCorado** [comment]
I was able to Install pyxcp v0.22.1 locally with `pip3 install -e .` I will be taking a look at those new features that v0.22.1 has


Thanks for the help!
