### ISSUE TITLE
unreliable socket.fileno() 

### ISSUE THREAD

**Issue by danielhrisca** [christoph2/pyxcp#77]
Hello all,

I've come across a very strange problem related to the value returned by `socket.fileno`. We use this to check if a socket connection was terminated on the slave side by comparing to -1 [here](https://github.com/christoph2/pyxcp/blob/master/pyxcp/transport/eth.py#L133),  but it looks like this is not reliable.

I've come to this after investigating another issue were the CPU usage would go to 100%. I finally was able to track it down to the same while loop. The problem was that after the server was closed the socket fileno remained the same, causing the `select` call to return immediately. This basically created a very tight while loop that consumed all the CPU.

To demonstrate this I've made this change to the while loop

```python
        while True:
            try:
                if close_event_set() or socket_fileno() == -1:
                    return
                t = perf_counter()
                sel = select(0.2)
                t = perf_counter()-t
                print('Select took',t)
                for _, events in sel:
                    if events & EVENT_READ:
                        if high_resolution_time:
                            recv_timestamp = time()
                        else:
                            recv_timestamp = timestamp_origin + perf_counter() - perf_counter_origin

                        if use_tcp:
                            _packets.append((sock_recv(RECV_SIZE), recv_timestamp))
                        else:
                            response, _ = sock_recv(Eth.MAX_DATAGRAM_SIZE)
                            _packets.append((response, recv_timestamp))
                            
                        if t < 0.001:
                            print(_packets[-1])
                print('Socket fileno = ', socket_fileno())
                sleep(0.2)
            except:
                self.status = 0  # disconnected
                break
```

and I've ran the test setup from the screen recording. When the CarMaker simulation is set to pause we can see the `select` call taking ~200ms. The the simulation is stopped and the application terminated, but the socket fileno remains unchanged and the `select` call returns immediately/.
![socket_problem](https://user-images.githubusercontent.com/20952040/136602310-9f8a8cca-734f-4930-bca3-816fd5c1697a.gif)

What could we use to check for the socket termination?

**Comment by christoph2** [comment]
Hi Daniel,
Nice to hear from you again!
The last few months were really hard for me (thanks to the TheCoronaBeast™...), but I'll soon continue to work.
My highly prioritized sub-project is indeed the C++ XcponEth extension module, which already exists in fragments (and hopefully will also solve your performance issues:-) )

Under the hood fileno() returns
s->sock_fd
and
s->sock_fd = INVALID_SOCKET;
is only executed by the following functions:
- sock_close
- sock_detach
- sock_finalise 
Meaning fileno() is absolutely useless to detect termination of the  peer connection..
