### ISSUE TITLE
pyxcp/transport/can.py listen function should check if len of frame.data is bigger than 0

### ISSUE THREAD

**Issue by nedlukasz** [christoph2/pyxcp#83]
There is possible that `frame = self.canInterface.read()` will return frame with len(frame.data) == 0. Frame with empty data will cause exception inside processResponse in code `pid = response[0]`.

Such case when Can Driver return frame with empty data exist for Kvaser Virtual Can Driver.

**Comment by danielhrisca** [comment]
The XCP frame must have at least the first data byte, so there is some other problem

**Comment by nedlukasz** [comment]
Yes, XCP frame must have at least one byte. Maybe better place for that check is inside pyxcp/transport/candriver/python_can.py. There is already in line 112 check about correctness of frame
`if frame is None or frame.arbitration_id != self.parent.can_id_master.id:
                return None `
and it can be extended as:
`if frame is None or frame.arbitration_id != self.parent.can_id_master.id or not len(frame.data):
                return None`
